---
#- name: set proxy
#  become: yes
#  copy:
#    dest: '{{ environment_proxy }}'
#    content: "http_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nhttps_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nftp_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nno_proxy=localhost,127.0.0.1,127.0.1.1,ubuntu"
- name: change authority
  raw: sudo chmod 775 /etc/environment

- name: set proxy
  tags: 'always'
  become: yes
  lineinfile:
    dest: '{{ environment_proxy }}'
    insertafter: EOF
    line: '{{ item }}'
  loop: '{{ proxy }}'