--- # Common vars
availability_zone: melbourne-qh2-uom #创建instance所选择的区域
security_groups:  #Security gourp #网络安全组协议
  - name: instance_ssh
    description: "Instance security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0 #允许连接服务器的外部ip（默认所有）
  - name: instance_http
    description: "Instance security group for HTTP"
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0 #同上
  - name: instance_couchdb
    description: "Instance port of couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0 #同上
instance_name1: Group18-Instance1
instance_name2: Group18-Instance2  #Instance
instance_name3: Group18-Instance3
instance_name4: Group18-Instance4
vol_name1: vol_instance1
vol_name2: vol_instance2
vol_name3: vol_instance3
vol_name4: vol_instance4
#proxy:
#    - 'http_proxy="http://wwwproxy.unimelb.edu.au:8000"'
#    - 'https_proxy="http://wwwproxy.unimelb.edu.au:8000"'
#    - 'ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"'
#    - 'no_proxy=localhost,127.0.0.1,127.0.1.1,ubuntu'
vol_size: 60
instance_image: 394a1b97-a8d3-4593-aab0-8156f0dfeeca #选择服务器上image，这是ubuntu16.04的image id
instance_key_name: Group18 #所用的key pair
instance_flavor: uom.mse.2c9g #所用的flavor 2vCPU，9G memory
environment_proxy: /etc/environment