--- #Create volumes from vars
- name: Create an volume1
  os_volume:
    name: '{{ vol_name1 }}'
    size: '{{ vol_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: present
  register: os_vol1
- debug:
    msg: "Volume {{ vol_name1 }} has been created."
  when: os_vol1.openstack is defined

- name: Create an volume2
  os_volume:
    name: '{{ vol_name2 }}'
    size: '{{ vol_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: present
  register: os_vol2
- debug:
    msg: "Volume {{ vol_name2 }} has been created."
  when: os_vol2.openstack is defined

- name: Create an volume3
  os_volume:
    name: '{{ vol_name3 }}'
    size: '{{ vol_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: present
  register: os_vol3
- debug:
    msg: "Volume {{ vol_name3 }} has been created."
  when: os_vol3.openstack is defined

- name: Create an volume4
  os_volume:
    name: '{{ vol_name4 }}'
    size: '{{ vol_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: present
  register: os_vol4
- debug:
    msg: "Volume {{ vol_name4 }} has been created."
  when: os_vol4.openstack is defined
