---
- name: remove former local git repo
  file:
    state: absent
    path: ~/xanthic

#- name: clone git repo
#  git:
#    repo: 'https://github.com/dogtwofly/xanthic.git'
#    dest: ~/xanthic

- name: clone git repo
  raw: git clone https://github.com/dogtwofly/xanthic.git