version: "3"
services:
  couch_master:           # 主机
    image: "couchdb:2.3.0"
    restart: always
    ports:
      - "5984:5984"
      - "5986:5986"
      - "4369:4369"
      - "9100-9200:9100-9200"
    links:
      - couch_slave1
      - couch_slave2
    volumes:
      - /
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=pass
      - NODENAME=172.20.0.2
    container_name: couch_master
    networks:
      couchdb_nw:
        ipv4_address:172.20.0.2
  couch_slave1:               # 1号子数据库
    image: "couchdb:2.3.0"
    restart: always
    ports:
      - "15984:5984"
    volumes:
      - 
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=pass
      - NODENAME=172.20.0.3
    container_name: couch_slave1
    network:
      couchdb_nw:
        ipv4_address: 172.20.0.3
  couch_slave2:
    image:"always"
    ports:
      - "25984:5984"
    volumes:
      -
    envrionment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=pass
      - NODENAME=172.20.0.4
networks:
  couchdb_nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16