---
#Create volume snapshot(s)
- name: Create Instance2-volume snapshot
  os_volume_snapshot:
    state: present
    volume: '{{ vol_name2 }}'
    name: "{{ vol_name2 }}-{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"
    wait: yes
    timeout: 600
    force: yes
    availability_zone: '{{ availability_zone }}'
  register: snapshot_instance2

- name: Create Instance4-volume snapshot
  os_volume_snapshot:
    state: present
    volume: '{{ vol_name4 }}'
    name: "{{ vol_name4 }}-{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"
    wait: yes
    timeout: 600
    force: yes
    availability_zone: '{{ availability_zone }}'
  register: snapshot_instance4